<?php
/**
 * Created by PhpStorm.
 * User: Я
 * Date: 13.03.2018
 * Time: 0:03
 */

class DerivedPeregruzca extends BasePeregruzca
{
    public function printVar()
    {
        parent::printVar(); // TODO: Change the autogenerated stub
        echo 'Вызов метода printVar() производного класса <br>';
    }
}